// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UsingsOrganizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "UsingsOrganizer.18485ab5-a172-4509-bd3e-fda39231ee58";
        public const string Name = "Usings Organizer";
        public const string Description = @"Visual Studio extension for sorting and organizing connected namespaces in a .cs files";
        public const string Language = "en-US";
        public const string Version = "0.1.3";
        public const string Author = "Igor Rakitskii";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
