// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UsingsOrganizer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UsingsOrganizerString = "55f579fd-2e4a-4196-a606-214bb3368b37";
        public static Guid UsingsOrganizer = new Guid(UsingsOrganizerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OrganizeUsingsMenuGroup = 0x0001;
        public const int OrganizeUsingsCommand = 0x0100;
    }
}
